VERSION = "2.0.0"

NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS = [
  "GDRLJC6EOKRR3BPKWGJPGI5GUN4GZFZRWQFDG3RJNZJEIBYA7B3EPROG",
  "GA4KUJWJB5JVWPEN5JXZKUGHXTHQZYQOKU2VX2OG5MFDFLJEXT4DEACC",
  "GATEB4Y7IKPXLSRSTH5GOUYA4ZAS6KQVP32BDPFF3GMSFKRKOSAYSDFI",
  "GB52W5JF4FP4WTJQQINFVGEPLEVYZWIF62YZP677632L65R7QEYEMVPF",
  "GD4H72QEA6Q5NKESCWLPVQJBCIWHXIUZEPTCIZUQSFR3AW3XBVB4MVPT",
]

[DOCUMENTATION]
ORG_NAME = "Programmers Guild of Montelibero Association"
ORG_URL = "https://mtlprog.xyz"

[[PRINCIPALS]]
name = "Stas Karkavin"
email = "stas@panarchy.now"
twitter = "staskarkavin"
github = "xdefrag"

[[CURRENCIES]]
code = "NUYEN"
issuer = "GDRLJC6EOKRR3BPKWGJPGI5GUN4GZFZRWQFDG3RJNZJEIBYA7B3EPROG"
display_decimals = 0

[[CURRENCIES]]
code = "MVP"
issuer = "GB52W5JF4FP4WTJQQINFVGEPLEVYZWIF62YZP677632L65R7QEYEMVPF"
display_decimals = 0

[[CURRENCIES]]
code = "MVPOffer"
issuer = "GD4H72QEA6Q5NKESCWLPVQJBCIWHXIUZEPTCIZUQSFR3AW3XBVB4MVPT"
fixed_number = 1
display_decimals = 7
